name: mod-tidy-action
description: 'Run go mod tidy on one or more go.mod files'

author: Evan Torrie <evantorrie@users.noreply.github.com>

inputs:
  gomods:
    description: 'go.mod files to run go mod tidy. Can be glob patterns one per line'
    required: true
    default: go.mod
  gosum_only:
    description: 'fail if files other than go.sum are modified during tidy'
    required: false
    default: false
  gomodsum_only:
    description: 'fail if files other than go.{mod,sum} are modified during tidy'
    required: false
    default: false
  remove_gosum:
    description: 'remove go.sum file as a first step before running go mod tidy'
    required: false
    default: false
  directives:
    description: 'supports setting one or more go directive when calling go mod tidy'
    required: false
    default: ""

outputs:
  changedfiles: # id of output
    description: 'List of files that were changed, one per line'

runs:
  using: 'node12'
  main: 'dist/index.js'
